site_name: Disgames
site_description: 3rd Party library for discord.py
repo_url: https://github.com/andrewthederp/Disgames
edit_uri: blob/main/docs/

nav:
  - Home:
    - Overiew: index.md
    - FAQ: faq.md
    - Table Of Contents: table-of-contents.md
  - Getting Started: 
    - Basic Bot: setups/basic-bot-setup.md
    - Advanced Bot: setups/advanced-bot-setup.md
  - Releases:
    - Changelog : changelog.md
  - Mixins:
    - BattleShip: mixins/battleship.md
    - Checkers: mixins/checkers.md
    - Chess: mixins/chess.md
    - Connect4: mixins/connect4.md
    - Hangman: mixins/hangman.md
    - Madlib: mixins/madlib.md
    - Minesweeper: mixins/minesweeper.md
    - RPS: mixins/rps.md
    - Snake: mixins/snake.md
    - SNL: mixins/snl.md
    - Sokoban: mixins/sokoban.md
    - Sudoko: mixins/sudoko.md
    - Tictactoe: mixins/tictactoe.md
    - 2048: mixins/2048.md

theme:
  name: material
  language: en
  features:
    - tabs
    - instant
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - navigation.sections
    - navigation.indexes
    - content.code.annotate
    - navigation.tabs    
  palette: 
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  logo: src/disgames.png
  favicon: src/disgames.ico
  features:
      - navigation.instant
      - navigation.tabs
      - navigation.top
      - content.tabs.link
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.keys
  - attr_list
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - pymdownx.betterem:
      smart_enable: all
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/andrewthederp/Disgames

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true